In [6]:
import random
import sys
import numpy as np
from yolo import YOLO
from PIL import Image
import cv2
import numpy as np
import collections


def insertion_sort(lst):
    if len(lst) == 1:
        return lst

    for i in range(1, len(lst)):
        temp = lst[i]
        j = i - 1
        while j >= 0 and temp < lst[j]:
            lst[j + 1] = lst[j]
            j -= 1
        lst[j + 1] = temp
    return lst

hls_list=[]
def main(yolo):
    img = 'C:/Users/user/Desktop/basketball/train/243.png'
    image = Image.open(img)
    image_cv = cv2.cvtColor(np.asarray(image),cv2.COLOR_RGB2BGR)  
      
    image_class, image_box = yolo.detect_image(image)
    person_box = []
    hls_list=[]
    for i, c in reversed(list(enumerate(image_class))):
            predicted_class = yolo.class_names[c]
            if predicted_class != 'person':
               continue
            person_box = image_box[i]
            
            top = max(0, np.floor(person_box[0] + 0.5).astype('int32'))            
            left = max(0, np.floor(person_box[1] + 0.5).astype('int32'))
            bottom = min(image.size[1], np.floor(person_box[2] + 0.5).astype('int32'))
            right = min(image.size[0], np.floor(person_box[3] + 0.5).astype('int32'))            
            x = int(left+(right-left)*1/6)
            y = int(top+(bottom-top)*1/6)
            w = int((right-left)*2/3)
            h = int((bottom-top)*1/2)
            crop_img= image_cv[y:y+h, x:x+w]
            hls = cv2.cvtColor(crop_img,cv2.COLOR_BGR2HLS)
            HLS = hls[int(h/2),int(w/2)]
            hls_list.append(HLS[1])
            
            print(HLS)
            cv2.imshow(str(HLS),crop_img)
            cv2.waitKey(0)
            cv2.destroyAllWindows()
    return hls_list


In [8]:
if __name__ == '__main__':
    hls_list = main(YOLO())
    print ("Original Data:", hls_list)
    sortData = insertion_sort(hls_list)
    print ("Sorted Data:", sortData)

model_data/yolo.h5 model, anchors, and classes loaded.
(416, 416, 3)
[133  51  75]
[ 8 96 29]
[130  66  80]
[160  39  20]
[  7  50 199]
[132  45  34]
[150  43  18]
[177  86  27]
[ 7 57 38]
[ 2 48 51]
[143  72  30]
[171 186  35]
[129  62  58]
[  8 132  33]
[124 198  76]
[128 171  44]
[155 208  49]
Original Data: [51, 96, 66, 39, 50, 45, 43, 86, 57, 48, 72, 186, 62, 132, 198, 171, 208]
Sorted Data: [39, 43, 45, 48, 50, 51, 57, 62, 66, 72, 86, 96, 132, 171, 186, 198, 208]
