In [3]:
import sys
import numpy as np
from yolo import YOLO
from PIL import Image
import cv2
import numpy as np
import collections

C:\Users\user\AppData\Roaming\Python\Python36\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [6]:
def main(yolo):
    img = 'C:/Users/user/Desktop/basketball/train/243.png'
    image = Image.open(img)
    image_cv = cv2.cvtColor(np.asarray(image),cv2.COLOR_RGB2BGR)  
      
    image_class, image_box = yolo.detect_image(image)
    person_box = []
    hls_list=[]
    for i, c in reversed(list(enumerate(image_class))):
            predicted_class = yolo.class_names[c]
            if predicted_class != 'person':
               continue
            person_box = image_box[i]
            
            top = max(0, np.floor(person_box[0] + 0.5).astype('int32'))            
            left = max(0, np.floor(person_box[1] + 0.5).astype('int32'))
            bottom = min(image.size[1], np.floor(person_box[2] + 0.5).astype('int32'))
            right = min(image.size[0], np.floor(person_box[3] + 0.5).astype('int32'))            
            x = int(left+(right-left)*1/6)
            y = int(top+(bottom-top)*1/6)
            w = int((right-left)*2/3)
            h = int((bottom-top)*1/2)
            crop_img= image_cv[y:y+h, x:x+w]
            hls = cv2.cvtColor(crop_img,cv2.COLOR_BGR2HLS)
            HLS = hls[int(h/2),int(w/2)]
            hls_list.append(HLS[1])
            
            print(HLS, hls_list)
            cv2.imshow(str(HLS),crop_img)
            cv2.waitKey(0)
            cv2.destroyAllWindows()



In [7]:
if __name__ == '__main__':
    main(YOLO())

model_data/yolo.h5 model, anchors, and classes loaded.
(416, 416, 3)
[133  51  75] [51]
[ 8 96 29] [51, 96]
[130  66  80] [51, 96, 66]
[160  39  20] [51, 96, 66, 39]
[  7  50 199] [51, 96, 66, 39, 50]
[132  45  34] [51, 96, 66, 39, 50, 45]
[150  43  18] [51, 96, 66, 39, 50, 45, 43]
[177  86  27] [51, 96, 66, 39, 50, 45, 43, 86]
[ 7 57 38] [51, 96, 66, 39, 50, 45, 43, 86, 57]
[ 2 48 51] [51, 96, 66, 39, 50, 45, 43, 86, 57, 48]
[143  72  30] [51, 96, 66, 39, 50, 45, 43, 86, 57, 48, 72]
[171 186  35] [51, 96, 66, 39, 50, 45, 43, 86, 57, 48, 72, 186]
[129  62  58] [51, 96, 66, 39, 50, 45, 43, 86, 57, 48, 72, 186, 62]
[  8 132  33] [51, 96, 66, 39, 50, 45, 43, 86, 57, 48, 72, 186, 62, 132]
[124 198  76] [51, 96, 66, 39, 50, 45, 43, 86, 57, 48, 72, 186, 62, 132, 198]
[128 171  44] [51, 96, 66, 39, 50, 45, 43, 86, 57, 48, 72, 186, 62, 132, 198, 171]
[155 208  49] [51, 96, 66, 39, 50, 45, 43, 86, 57, 48, 72, 186, 62, 132, 198, 171, 208]
