In [1]:
import sys
import numpy as np
from yolo import YOLO
from PIL import Image
import cv2


C:\Users\user\AppData\Roaming\Python\Python36\site-packages\h5py\__init__.py:34: FutureWarning: Conversion of the second argument of issubdtype from `float` to `np.floating` is deprecated. In future, it will be treated as `np.float64 == np.dtype(float).type`.
  from ._conv import register_converters as _register_converters
Using TensorFlow backend.


In [2]:

def main(yolo):
    img = 'C:/Users/user/Desktop/basketball/train/243.png'
    image = Image.open(img)
    image_cv = cv2.cvtColor(np.asarray(image),cv2.COLOR_RGB2BGR)  
      
    image_class, image_box = yolo.detect_image(image)
    person_box = []
    for i, c in reversed(list(enumerate(image_class))):
            predicted_class = yolo.class_names[c]
            if predicted_class != 'person':
               continue
            person_box = image_box[i]
            
            
            top = max(0, np.floor(person_box[0] + 0.5).astype('int32'))            
            left = max(0, np.floor(person_box[1] + 0.5).astype('int32'))
            bottom = min(image.size[1], np.floor(person_box[2] + 0.5).astype('int32'))
            right = min(image.size[0], np.floor(person_box[3] + 0.5).astype('int32'))            
            x = int(left+(right-left)*1/6)
            y = int(top+(bottom-top)*1/6)
            w = int((right-left)*2/3)
            h = int((bottom-top)*1/2)
            crop_img= image_cv[y:y+h, x:x+w]
            hsv = cv2.cvtColor(crop_img,cv2.COLOR_BGR2HSV)
            HSV = hsv[int(h/2),int(w/2)]
            print(HSV)
            cv2.imshow(str(HSV[1]),crop_img )
            cv2.waitKey(0)
            cv2.destroyAllWindows()

In [3]:
if __name__ == '__main__':
    main(YOLO())

model_data/yolo.h5 model, anchors, and classes loaded.
(416, 416, 3)
[133 116  66]
[  8  52 107]
[130 122  86]
[160  36  42]
[  7 223  89]
[133  60  51]
[150  33  46]
[177  48  95]
[ 7 67 65]
[ 2 85 57]
[143  54  80]
[171  25 195]
[129  94  76]
[  8  55 148]
[124  40 215]
[128  40 185]
[155  21 217]
